SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
    INNER JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.ITEM_ID NOT IN (SELECT DISTINCT IFNULL(B.PARENT_ITEM_ID, 100) FROM ITEM_TREE B)
ORDER BY A.ITEM_ID DESC;